version: '3.8'
networks:
   mahesh:
services:
  movies:
    image: mahesh147/mymovies:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3
    network:
      - mahesh
  train:
    image: mahesh147/mytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: mahesh147/mydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: mahesh147/myrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
